# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
jl_box_bool <- function(x) {
    .Call('_juliaapi_juliaapi_box_bool', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_int8 <- function(x) {
    .Call('_juliaapi_juliaapi_box_int8', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_uint8 <- function(x) {
    .Call('_juliaapi_juliaapi_box_uint8', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_int16 <- function(x) {
    .Call('_juliaapi_juliaapi_box_int16', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_uint16 <- function(x) {
    .Call('_juliaapi_juliaapi_box_uint16', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_int32 <- function(x) {
    .Call('_juliaapi_juliaapi_box_int32', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_uint32 <- function(x) {
    .Call('_juliaapi_juliaapi_box_uint32', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_char <- function(x) {
    .Call('_juliaapi_juliaapi_box_char', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_int64 <- function(x) {
    .Call('_juliaapi_juliaapi_box_int64', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_uint64 <- function(x) {
    .Call('_juliaapi_juliaapi_box_uint64', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_float32 <- function(x) {
    .Call('_juliaapi_juliaapi_box_float32', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_float64 <- function(x) {
    .Call('_juliaapi_juliaapi_box_float64', PACKAGE = 'juliaapi', x)
}

#' @export
jl_box_voidpointer <- function(x) {
    .Call('_juliaapi_juliaapi_box_voidpointer', PACKAGE = 'juliaapi', x)
}

juliaapi_init <- function(libpath) {
    .Call('_juliaapi_juliaapi_init', PACKAGE = 'juliaapi', libpath)
}

jl_is_null_xptr <- function(t) {
    .Call('_juliaapi_jl_is_null_xptr', PACKAGE = 'juliaapi', t)
}

jl_set_xptr <- function(t, name) {
    invisible(.Call('_juliaapi_jl_set_xptr', PACKAGE = 'juliaapi', t, name))
}

#' @export
NULL

#' @export
jl_eval_string <- function(str) {
    .Call('_juliaapi_juliaapi_eval_string', PACKAGE = 'juliaapi', str)
}

jl_exception_occurred <- function() {
    .Call('_juliaapi_julia_exception_occurred', PACKAGE = 'juliaapi')
}

#' @export
jl_get_function <- function(module, str) {
    .Call('_juliaapi_juliaapi_get_function', PACKAGE = 'juliaapi', module, str)
}

#' @export
jl_call0 <- function(f) {
    .Call('_juliaapi_juliaapi_call0', PACKAGE = 'juliaapi', f)
}

#' @export
jl_call1 <- function(f, a) {
    .Call('_juliaapi_juliaapi_call1', PACKAGE = 'juliaapi', f, a)
}

#' @export
jl_call2 <- function(f, a, b) {
    .Call('_juliaapi_jualiapi_call2', PACKAGE = 'juliaapi', f, a, b)
}

#' @export
jl_call3 <- function(f, a, b, c) {
    .Call('_juliaapi_jualiapi_call3', PACKAGE = 'juliaapi', f, a, b, c)
}

#' @export
jl_isa <- function(a, t) {
    .Call('_juliaapi_juliaapi_isa', PACKAGE = 'juliaapi', a, t)
}

#' @export
jl_types_equal <- function(a, b) {
    .Call('_juliaapi_juliaapi_types_equal', PACKAGE = 'juliaapi', a, b)
}

#' @export
jl_typename_str <- function(v) {
    .Call('_juliaapi_juliaapi_typename_str', PACKAGE = 'juliaapi', v)
}

#' @export
jl_typeof_str <- function(v) {
    .Call('_juliaapi_juliaapi_typeof_str', PACKAGE = 'juliaapi', v)
}

#' @export
jl_symbol <- function(str) {
    .Call('_juliaapi_juliaapi_symbol', PACKAGE = 'juliaapi', str)
}

#' @export
jl_unbox_bool <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_bool', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_int8 <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_int8', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_uint8 <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_uint8', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_int16 <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_int16', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_uint16 <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_uint16', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_int32 <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_int32', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_uint32 <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_uint32', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_int64 <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_int64', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_uint64 <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_uint64', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_float32 <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_float32', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_float64 <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_float64', PACKAGE = 'juliaapi', v)
}

#' @export
jl_unbox_voidpointer <- function(v) {
    .Call('_juliaapi_juliaapi_unbox_voidpointer', PACKAGE = 'juliaapi', v)
}

#' @export
jl_is_initialized <- function() {
    .Call('_juliaapi_juliaapi_is_initialized', PACKAGE = 'juliaapi')
}

#' @export
jl_show <- function(t) {
    invisible(.Call('_juliaapi_juliaapi_show', PACKAGE = 'juliaapi', t))
}

#' @export
jl_check_exception <- function() {
    invisible(.Call('_juliaapi_juliaapi_check_exception', PACKAGE = 'juliaapi'))
}

